### ISSUE TITLE
DCRDGTE name too long

### ISSUE THREAD

**Issue by bjpetit** [gncnpk/dcdgte#1]
I did find one issue to file. The name DCRDGTE is one character too long. The AX.25 address specification allows for 6 alphanumeric characters as well as an SSID of 0-15.
Some programs appear to allow the longer name and it seems to do ok on APRS-IS. But I'm guessing this address may not get very far on RF. For example, my yeasu radio cannot send to that address.

**Comment by gncnpk** [comment]
What do you think about DCDGTE?

**Comment by bjpetit** [comment]
That makes sense. Actually, I took the script a bit ago and changed it to that exact name to test sending from a radio. That worked from my HT.
https://aprs.fi/?c=message&call=WG0A-9

<img width="586" alt="Screenshot 2023-07-20 at 8 29 00 PM" src="https://github.com/gncnpk/dcrdgte/assets/11699403/d1ea6896-17eb-4183-9a85-524f1fd43b62">
The first message in discord was me dumping out the raw message, just to see it.
One caveat. The webhook doesn't send acks for the messages, so the radio continues to send the message until it times out. Which is why you see a bunch of messages. The extras are retrys.

**Comment by gncnpk** [comment]
Is there way to respond with a ACK while abiding by the laws, rules and regulations? And allow for two-way communication?

**Comment by bjpetit** [comment]
You could send an ack with something like this.
https://github.com/bjpetit/dcrdgte/commit/42745570e15576c47732522ebcc1847f5e6ce02e
There's a bunch of other noise in that commit from my playing around with things.
This appears to work. But probably isn't 100% correct. You'd want to use a real call when logging into aprsis. Then you would, sort of be responsible for those packets as the owner of the script.
While not full 2-way comms, it can at least ack messages. And the script could use that call to do other types of packets.

**Comment by gncnpk** [comment]
Hey Brent!

I got this all solved in https://github.com/gncnpk/dcdgte/commit/e7999df0cb8920379402d9d833f70c76d04aae69

Let me know if there are any other issues/questions/concerns/feedback!
